name: Reporte

on:
    push
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Instalar Python 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: SECRET PROCESS

      run: |
        python Propio.py

    - uses: stefanzweifel/git-auto-commit-action@v2
      with:
        commit_message: "Descargado archivos"
        branch: main
        # Optional glob pattern of files which should be added to the commit
        #file_pattern: /

        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: Actions Bot
        commit_user_email: lmonsalve22@gmail.com
        commit_author: BOT <lmonsalve22@gmail.com>
        push_options: '--force'
